# Generated by Django 4.0.3 on 2022-03-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainflat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flat',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AddField(
            model_name='flat',
            name='image',
            field=models.ImageField(blank=True, upload_to='flat_photo'),
        ),
    ]
